# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mewfl/mkit

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mewfl/mkit

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mewfl/mkit/CMakeFiles /home/mewfl/mkit//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mewfl/mkit/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mkit

# Build rule for target.
mkit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mkit
.PHONY : mkit

# fast build rule for target.
mkit/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/build
.PHONY : mkit/fast

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mkit/camera.o: src/mkit/camera.cpp.o
.PHONY : src/mkit/camera.o

# target to build an object file
src/mkit/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/camera.cpp.o
.PHONY : src/mkit/camera.cpp.o

src/mkit/camera.i: src/mkit/camera.cpp.i
.PHONY : src/mkit/camera.i

# target to preprocess a source file
src/mkit/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/camera.cpp.i
.PHONY : src/mkit/camera.cpp.i

src/mkit/camera.s: src/mkit/camera.cpp.s
.PHONY : src/mkit/camera.s

# target to generate assembly for a file
src/mkit/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/camera.cpp.s
.PHONY : src/mkit/camera.cpp.s

src/mkit/controller.o: src/mkit/controller.cpp.o
.PHONY : src/mkit/controller.o

# target to build an object file
src/mkit/controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/controller.cpp.o
.PHONY : src/mkit/controller.cpp.o

src/mkit/controller.i: src/mkit/controller.cpp.i
.PHONY : src/mkit/controller.i

# target to preprocess a source file
src/mkit/controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/controller.cpp.i
.PHONY : src/mkit/controller.cpp.i

src/mkit/controller.s: src/mkit/controller.cpp.s
.PHONY : src/mkit/controller.s

# target to generate assembly for a file
src/mkit/controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/controller.cpp.s
.PHONY : src/mkit/controller.cpp.s

src/mkit/mesh.o: src/mkit/mesh.cpp.o
.PHONY : src/mkit/mesh.o

# target to build an object file
src/mkit/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/mesh.cpp.o
.PHONY : src/mkit/mesh.cpp.o

src/mkit/mesh.i: src/mkit/mesh.cpp.i
.PHONY : src/mkit/mesh.i

# target to preprocess a source file
src/mkit/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/mesh.cpp.i
.PHONY : src/mkit/mesh.cpp.i

src/mkit/mesh.s: src/mkit/mesh.cpp.s
.PHONY : src/mkit/mesh.s

# target to generate assembly for a file
src/mkit/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/mesh.cpp.s
.PHONY : src/mkit/mesh.cpp.s

src/mkit/object2D.o: src/mkit/object2D.cpp.o
.PHONY : src/mkit/object2D.o

# target to build an object file
src/mkit/object2D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/object2D.cpp.o
.PHONY : src/mkit/object2D.cpp.o

src/mkit/object2D.i: src/mkit/object2D.cpp.i
.PHONY : src/mkit/object2D.i

# target to preprocess a source file
src/mkit/object2D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/object2D.cpp.i
.PHONY : src/mkit/object2D.cpp.i

src/mkit/object2D.s: src/mkit/object2D.cpp.s
.PHONY : src/mkit/object2D.s

# target to generate assembly for a file
src/mkit/object2D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/object2D.cpp.s
.PHONY : src/mkit/object2D.cpp.s

src/mkit/object3D.o: src/mkit/object3D.cpp.o
.PHONY : src/mkit/object3D.o

# target to build an object file
src/mkit/object3D.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/object3D.cpp.o
.PHONY : src/mkit/object3D.cpp.o

src/mkit/object3D.i: src/mkit/object3D.cpp.i
.PHONY : src/mkit/object3D.i

# target to preprocess a source file
src/mkit/object3D.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/object3D.cpp.i
.PHONY : src/mkit/object3D.cpp.i

src/mkit/object3D.s: src/mkit/object3D.cpp.s
.PHONY : src/mkit/object3D.s

# target to generate assembly for a file
src/mkit/object3D.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/object3D.cpp.s
.PHONY : src/mkit/object3D.cpp.s

src/mkit/renderer.o: src/mkit/renderer.cpp.o
.PHONY : src/mkit/renderer.o

# target to build an object file
src/mkit/renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/renderer.cpp.o
.PHONY : src/mkit/renderer.cpp.o

src/mkit/renderer.i: src/mkit/renderer.cpp.i
.PHONY : src/mkit/renderer.i

# target to preprocess a source file
src/mkit/renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/renderer.cpp.i
.PHONY : src/mkit/renderer.cpp.i

src/mkit/renderer.s: src/mkit/renderer.cpp.s
.PHONY : src/mkit/renderer.s

# target to generate assembly for a file
src/mkit/renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/renderer.cpp.s
.PHONY : src/mkit/renderer.cpp.s

src/mkit/shader.o: src/mkit/shader.cpp.o
.PHONY : src/mkit/shader.o

# target to build an object file
src/mkit/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/shader.cpp.o
.PHONY : src/mkit/shader.cpp.o

src/mkit/shader.i: src/mkit/shader.cpp.i
.PHONY : src/mkit/shader.i

# target to preprocess a source file
src/mkit/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/shader.cpp.i
.PHONY : src/mkit/shader.cpp.i

src/mkit/shader.s: src/mkit/shader.cpp.s
.PHONY : src/mkit/shader.s

# target to generate assembly for a file
src/mkit/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/shader.cpp.s
.PHONY : src/mkit/shader.cpp.s

src/mkit/window.o: src/mkit/window.cpp.o
.PHONY : src/mkit/window.o

# target to build an object file
src/mkit/window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/window.cpp.o
.PHONY : src/mkit/window.cpp.o

src/mkit/window.i: src/mkit/window.cpp.i
.PHONY : src/mkit/window.i

# target to preprocess a source file
src/mkit/window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/window.cpp.i
.PHONY : src/mkit/window.cpp.i

src/mkit/window.s: src/mkit/window.cpp.s
.PHONY : src/mkit/window.s

# target to generate assembly for a file
src/mkit/window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/mkit/window.cpp.s
.PHONY : src/mkit/window.cpp.s

src/voidbreach/voidbreach.o: src/voidbreach/voidbreach.cpp.o
.PHONY : src/voidbreach/voidbreach.o

# target to build an object file
src/voidbreach/voidbreach.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/voidbreach/voidbreach.cpp.o
.PHONY : src/voidbreach/voidbreach.cpp.o

src/voidbreach/voidbreach.i: src/voidbreach/voidbreach.cpp.i
.PHONY : src/voidbreach/voidbreach.i

# target to preprocess a source file
src/voidbreach/voidbreach.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/voidbreach/voidbreach.cpp.i
.PHONY : src/voidbreach/voidbreach.cpp.i

src/voidbreach/voidbreach.s: src/voidbreach/voidbreach.cpp.s
.PHONY : src/voidbreach/voidbreach.s

# target to generate assembly for a file
src/voidbreach/voidbreach.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/mkit.dir/build.make CMakeFiles/mkit.dir/src/voidbreach/voidbreach.cpp.s
.PHONY : src/voidbreach/voidbreach.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mkit"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mkit/camera.o"
	@echo "... src/mkit/camera.i"
	@echo "... src/mkit/camera.s"
	@echo "... src/mkit/controller.o"
	@echo "... src/mkit/controller.i"
	@echo "... src/mkit/controller.s"
	@echo "... src/mkit/mesh.o"
	@echo "... src/mkit/mesh.i"
	@echo "... src/mkit/mesh.s"
	@echo "... src/mkit/object2D.o"
	@echo "... src/mkit/object2D.i"
	@echo "... src/mkit/object2D.s"
	@echo "... src/mkit/object3D.o"
	@echo "... src/mkit/object3D.i"
	@echo "... src/mkit/object3D.s"
	@echo "... src/mkit/renderer.o"
	@echo "... src/mkit/renderer.i"
	@echo "... src/mkit/renderer.s"
	@echo "... src/mkit/shader.o"
	@echo "... src/mkit/shader.i"
	@echo "... src/mkit/shader.s"
	@echo "... src/mkit/window.o"
	@echo "... src/mkit/window.i"
	@echo "... src/mkit/window.s"
	@echo "... src/voidbreach/voidbreach.o"
	@echo "... src/voidbreach/voidbreach.i"
	@echo "... src/voidbreach/voidbreach.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

